---
id: Imap_Client
name: Imap_Client
full: IMAP client library
description: >-
  A library to access IMAP4rev1 (RFC 3501) mail servers. Also supports
  connections to POP3 (STD 53/RFC 1939).
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Imap_Client
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/mail: ^3
      horde/mime: ^3
      horde/socket_client: ^3
      horde/stream: ^2
      horde/secret: ^3
      horde/stream_filter: ^3
      horde/translation: ^3
      horde/util: ^3
    ext:
      hash: '*'
      json: '*'
  optional:
    composer:
      horde/cache: ^3
      horde/compress_fast: ^2
      horde/crypt_blowfish: ^2
      horde/db: ^3
      horde/hashtable: ^2
      horde/mongo: ^2
      horde/pack: ^2
      horde/stringprep: ^2
      horde/support: ^3
      horde/test: ^3
    ext:
      intl: '*'
      mbstring: '*'
